[workspace]
resolver = "3"
members = [
    "crates/domain",
    "crates/app",
    "crates/db",
    "crates/linux-app",
]

[workspace.package]
authors = ["Miroslav Krýsl <mkrysl@proton.me>"]
description = "Message-oriented life organizer"
edition = "2024"
license = "AGPL-3"
repository = "https://github.com/miroslavkrysl/wilycat"
rust-version = "1.91.0"
version = "0.1.0"

[workspace.dependencies]
uuid = "1.19.0"
serde = "1.0.228"
time = "0.3.45"