[workspace]
resolver = "3"
members = [
    "crates/core",
    "crates/db-turso",
    "crates/app-linux",
    "crates/playground",
]

[workspace.package]
authors = ["Miroslav Krýsl <mkrysl@proton.me>"]
description = "Message-oriented life organizer"
edition = "2024"
license = "AGPL-3"
repository = "https://github.com/miroslavkrysl/wilycat"
rust-version = "1.91.0"
version = "0.1.0"

[workspace.dependencies]
core = { path = "crates/core" }

uuid = "1.19.0"
serde = "1.0.228"
time = "0.3.45"
thiserror = "2.0.17"
anyhow = "1.0.100"
async-trait = "0.1.89"
futures = "0.3.31"
mockall = "0.14.0"
tokio = "1.49.0"
assertables = "9.8.4"