[workspace]
resolver = "3"
members = [
    "crates/core",
    "crates/db-turso",
    "crates/app-linux",
]

[workspace.package]
authors = ["Miroslav Krýsl <mkrysl@proton.me>"]
description = "Message-oriented life organizer"
edition = "2024"
license = "AGPL-3"
repository = "https://github.com/miroslavkrysl/wilycat"
rust-version = "1.95.0"
version = "0.1.0"

[workspace.dependencies]
core = { path = "crates/core" }

uuid = "1.20.0"
serde = "1.0.228"
time = "0.3.47"
async-trait = "0.1.89"
futures = "0.3.31"
unimock = "0.6.8"
tokio = "1.49.0"
assertables = "9.8.4"
indoc = "2.0.7"
turso = "0.5.0-pre.8"
tempfile = "3.25.0"
snafu = "0.8.9"