[package]
name = "core"
authors.workspace = true
description.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
snafu = { workspace = true }
unimock = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true, features = [] }
serde = { workspace = true, features = ["derive"] }
time = { workspace = true, features = ["serde"] }
uuid = { workspace = true, features = ["v7", "serde"] }
tokio = { workspace = true, features = ["rt", "macros"] }

[dev-dependencies]
assertables = { workspace = true }